apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  type: ClusterIP
  selector:
    app: scaletestapp
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http